# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'chat_untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(789, 475)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.PopUpAniStackedWidget = PopUpAniStackedWidget(self.centralwidget)
        self.PopUpAniStackedWidget.setObjectName("PopUpAniStackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.gridLayout = QtWidgets.QGridLayout(self.page)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout_39 = QtWidgets.QVBoxLayout()
        self.verticalLayout_39.setObjectName("verticalLayout_39")
        self.SegmentedWidget = SegmentedWidget(self.page)
        self.SegmentedWidget.setObjectName("SegmentedWidget")
        self.verticalLayout_39.addWidget(self.SegmentedWidget)
        self.linkpeople_name_listWidget = QtWidgets.QListWidget(self.page)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.linkpeople_name_listWidget.setFont(font)
        self.linkpeople_name_listWidget.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.linkpeople_name_listWidget.setStyleSheet("border:none;\n"
"background-color: transparent;")
        self.linkpeople_name_listWidget.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.linkpeople_name_listWidget.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.linkpeople_name_listWidget.setAutoScrollMargin(16)
        self.linkpeople_name_listWidget.setObjectName("linkpeople_name_listWidget")
        self.verticalLayout_39.addWidget(self.linkpeople_name_listWidget)
        self.gridLayout.addLayout(self.verticalLayout_39, 0, 0, 1, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(89)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.sip_lineEdit = LineEdit(self.page)
        self.sip_lineEdit.setObjectName("sip_lineEdit")
        self.horizontalLayout.addWidget(self.sip_lineEdit)
        self.target_name = SubtitleLabel(self.page)
        self.target_name.setObjectName("target_name")
        self.horizontalLayout.addWidget(self.target_name)
        self.SubtitleLabel = SubtitleLabel(self.page)
        self.SubtitleLabel.setObjectName("SubtitleLabel")
        self.horizontalLayout.addWidget(self.SubtitleLabel)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.frame = QtWidgets.QFrame(self.page)
        self.frame.setStyleSheet("background-color: transparent;\n"
"border:1px solid #34495e;\n"
"")
        self.frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.gridLayout_3.addLayout(self.verticalLayout_3, 1, 0, 1, 1)
        self.CommandBar = CommandBar(self.frame)
        self.CommandBar.setObjectName("CommandBar")
        self.gridLayout_3.addWidget(self.CommandBar, 0, 0, 1, 1)
        self.verticalLayout.addWidget(self.frame)
        self.chat_TextEdit = TextEdit(self.page)
        self.chat_TextEdit.setObjectName("chat_TextEdit")
        self.verticalLayout.addWidget(self.chat_TextEdit)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.pushButtonLeft = PrimaryPushButton(self.page)
        self.pushButtonLeft.setObjectName("pushButtonLeft")
        self.horizontalLayout_4.addWidget(self.pushButtonLeft)
        self.PrimaryPushButton = PrimaryPushButton(self.page)
        self.PrimaryPushButton.setObjectName("PrimaryPushButton")
        self.horizontalLayout_4.addWidget(self.PrimaryPushButton)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.verticalLayout.setStretch(1, 3)
        self.verticalLayout.setStretch(2, 1)
        self.gridLayout.addLayout(self.verticalLayout, 0, 1, 1, 1)
        self.gridLayout.setColumnStretch(0, 1)
        self.gridLayout.setColumnStretch(1, 4)
        self.PopUpAniStackedWidget.addWidget(self.page)
        self.gridLayout_2.addWidget(self.PopUpAniStackedWidget, 0, 0, 1, 1)
        self.gridLayout_2.setColumnStretch(0, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.PopUpAniStackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.sip_lineEdit.setText(_translate("MainWindow", "111113"))
        self.sip_lineEdit.setPlaceholderText(_translate("MainWindow", "目标sip号"))
        self.target_name.setText(_translate("MainWindow", "张三"))
        self.SubtitleLabel.setText(_translate("MainWindow", "在线中..."))
        self.chat_TextEdit.setPlaceholderText(_translate("MainWindow", "请输入您的聊天内容"))
        self.pushButtonLeft.setText(_translate("MainWindow", "左发送"))
        self.PrimaryPushButton.setText(_translate("MainWindow", "发送"))
from qfluentwidgets import CommandBar, LineEdit, PopUpAniStackedWidget, PrimaryPushButton, SegmentedWidget, SubtitleLabel, TextEdit
